<?php

namespace Database\Seeders;

use App\Models\Module;
use App\Models\RoleModulePermission;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;

class DefaultPermissionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * This seeds default permissions based on the current role-based access control
     * defined in routes/web.php
     */
    public function run(): void
    {
        $this->command->info('Seeding default permissions...');

        // Get all roles and modules
        $roles = Role::all()->keyBy('name');
        $modules = Module::all()->keyBy('slug');

        // Define default permissions for each role
        $defaultPermissions = [
            'Super Admin' => [
                // Super Admin gets full access to everything
                'ems' => 'full',
                'attendance' => 'full',
                'dock' => 'full',
                'holidays' => 'full',
                'leads' => 'full',
                'sales' => 'full',
                'issuance' => 'full',
                'qa-review' => 'full',
                'bank-verification' => 'full',
                'peregrine' => 'full',
                'ravens' => 'full',
                'retention' => 'full',
                'chargebacks' => 'full',
                'partners' => 'full',
                'carriers' => 'full',
                'payroll' => 'full',
                'chart-of-accounts' => 'full',
                'general-ledger' => 'full',
                'petty-cash' => 'full',
                'pabs-tickets' => 'full',
                'revenue-analytics' => 'full',
                'live-analytics' => 'full',
                'users' => 'full',
                'settings' => 'full',
                'audit-logs' => 'full',
                'duplicate-checker' => 'full',
                'epms' => 'full',
                'chat' => 'full',
                'announcements' => 'full',
            ],
            
            'CEO' => [
                'ems' => 'full',
                'attendance' => 'full',
                'dock' => 'full',
                'holidays' => 'full',
                'leads' => 'full',
                'sales' => 'full',
                'issuance' => 'full',
                'qa-review' => 'full',
                'bank-verification' => 'full',
                'peregrine' => 'full',
                'ravens' => 'full',
                'retention' => 'full',
                'chargebacks' => 'full',
                'partners' => 'full',
                'carriers' => 'full',
                'payroll' => 'full',
                'chart-of-accounts' => 'full',
                'general-ledger' => 'full',
                'petty-cash' => 'full',
                'pabs-tickets' => 'full',
                'revenue-analytics' => 'full',
                'live-analytics' => 'full',
                'users' => 'full',
                'settings' => 'view',
                'audit-logs' => 'view',
                'duplicate-checker' => 'full',
                'epms' => 'full',
                'chat' => 'full',
                'announcements' => 'full',
            ],

            'Manager' => [
                'ems' => 'full',
                'attendance' => 'full',
                'dock' => 'full',
                'holidays' => 'full',
                'leads' => 'full',
                'sales' => 'full',
                'issuance' => 'full',
                'qa-review' => 'full',
                'bank-verification' => 'full',
                'peregrine' => 'full',
                'ravens' => 'full',
                'retention' => 'full',
                'chargebacks' => 'full',
                'partners' => 'full',
                'carriers' => 'full',
                'payroll' => 'view',
                'chart-of-accounts' => 'full',
                'general-ledger' => 'full',
                'petty-cash' => 'view',
                'pabs-tickets' => 'full',
                'revenue-analytics' => 'full',
                'live-analytics' => 'full',
                'users' => 'edit',
                'settings' => 'view',
                'audit-logs' => 'view',
                'duplicate-checker' => 'full',
                'epms' => 'view',
                'chat' => 'full',
                'announcements' => 'full',
            ],

            'Co-ordinator' => [
                'ems' => 'full',
                'attendance' => 'full',
                'dock' => 'full',
                'holidays' => 'full',
                'leads' => 'edit',
                'sales' => 'full',
                'issuance' => 'full',
                'qa-review' => 'full',
                'bank-verification' => 'full',
                'peregrine' => 'full',
                'ravens' => 'full',
                'retention' => 'full',
                'chargebacks' => 'full',
                'partners' => 'full',
                'carriers' => 'full',
                'payroll' => 'full',
                'chart-of-accounts' => 'full',
                'general-ledger' => 'full',
                'petty-cash' => 'full',
                'pabs-tickets' => 'full',
                'revenue-analytics' => 'full',
                'live-analytics' => 'full',
                'users' => 'full',
                'settings' => 'view',
                'audit-logs' => 'full',
                'duplicate-checker' => 'full',
                'epms' => 'view',
                'chat' => 'full',
                'announcements' => 'full',
            ],

            'HR' => [
                'ems' => 'full',
                'attendance' => 'full',
                'dock' => 'edit',
                'holidays' => 'full',
                'leads' => 'none',
                'sales' => 'view',
                'issuance' => 'view',
                'qa-review' => 'view',
                'bank-verification' => 'none',
                'peregrine' => 'none',
                'ravens' => 'none',
                'retention' => 'view',
                'chargebacks' => 'view',
                'partners' => 'view',
                'carriers' => 'view',
                'payroll' => 'view',
                'chart-of-accounts' => 'none',
                'general-ledger' => 'none',
                'petty-cash' => 'none',
                'pabs-tickets' => 'none',
                'revenue-analytics' => 'none',
                'live-analytics' => 'none',
                'users' => 'edit',
                'settings' => 'none',
                'audit-logs' => 'none',
                'duplicate-checker' => 'none',
                'epms' => 'none',
                'chat' => 'full',
                'announcements' => 'view',
            ],

            'Trainer' => [
                'ems' => 'view',
                'attendance' => 'full',
                'dock' => 'view',
                'holidays' => 'view',
                'leads' => 'none',
                'sales' => 'view',
                'issuance' => 'view',
                'qa-review' => 'none',
                'bank-verification' => 'none',
                'peregrine' => 'none',
                'ravens' => 'none',
                'retention' => 'none',
                'chargebacks' => 'none',
                'partners' => 'none',
                'carriers' => 'none',
                'payroll' => 'none',
                'chart-of-accounts' => 'none',
                'general-ledger' => 'none',
                'petty-cash' => 'none',
                'pabs-tickets' => 'none',
                'revenue-analytics' => 'none',
                'live-analytics' => 'none',
                'users' => 'none',
                'settings' => 'none',
                'audit-logs' => 'none',
                'duplicate-checker' => 'none',
                'epms' => 'none',
                'chat' => 'full',
                'announcements' => 'view',
            ],

            'QA' => [
                'ems' => 'view',
                'attendance' => 'view',
                'dock' => 'full',
                'holidays' => 'view',
                'leads' => 'view',
                'sales' => 'view',
                'issuance' => 'view',
                'qa-review' => 'full',
                'bank-verification' => 'view',
                'peregrine' => 'view',
                'ravens' => 'view',
                'retention' => 'view',
                'chargebacks' => 'view',
                'partners' => 'none',
                'carriers' => 'none',
                'payroll' => 'none',
                'chart-of-accounts' => 'none',
                'general-ledger' => 'none',
                'petty-cash' => 'none',
                'pabs-tickets' => 'none',
                'revenue-analytics' => 'none',
                'live-analytics' => 'none',
                'users' => 'none',
                'settings' => 'none',
                'audit-logs' => 'none',
                'duplicate-checker' => 'none',
                'epms' => 'none',
                'chat' => 'full',
                'announcements' => 'view',
            ],

            'QA Officer' => [
                'ems' => 'view',
                'attendance' => 'view',
                'dock' => 'full',
                'holidays' => 'view',
                'leads' => 'view',
                'sales' => 'edit',
                'issuance' => 'view',
                'qa-review' => 'full',
                'bank-verification' => 'view',
                'peregrine' => 'view',
                'ravens' => 'view',
                'retention' => 'view',
                'chargebacks' => 'view',
                'partners' => 'none',
                'carriers' => 'none',
                'payroll' => 'none',
                'chart-of-accounts' => 'none',
                'general-ledger' => 'none',
                'petty-cash' => 'none',
                'pabs-tickets' => 'none',
                'revenue-analytics' => 'none',
                'live-analytics' => 'none',
                'users' => 'none',
                'settings' => 'none',
                'audit-logs' => 'none',
                'duplicate-checker' => 'none',
                'epms' => 'none',
                'chat' => 'full',
                'announcements' => 'view',
            ],

            'Employee' => [
                'ems' => 'none',
                'attendance' => 'view',
                'dock' => 'view',
                'holidays' => 'view',
                'leads' => 'none',
                'sales' => 'edit',
                'issuance' => 'view',
                'qa-review' => 'none',
                'bank-verification' => 'none',
                'peregrine' => 'none',
                'ravens' => 'none',
                'retention' => 'view',
                'chargebacks' => 'view',
                'partners' => 'none',
                'carriers' => 'none',
                'payroll' => 'none',
                'chart-of-accounts' => 'none',
                'general-ledger' => 'none',
                'petty-cash' => 'none',
                'pabs-tickets' => 'none',
                'revenue-analytics' => 'none',
                'live-analytics' => 'none',
                'users' => 'none',
                'settings' => 'none',
                'audit-logs' => 'none',
                'duplicate-checker' => 'none',
                'epms' => 'none',
                'chat' => 'full',
                'announcements' => 'view',
            ],

            'Agent' => [
                'ems' => 'none',
                'attendance' => 'view',
                'dock' => 'view',
                'holidays' => 'view',
                'leads' => 'none',
                'sales' => 'edit',
                'issuance' => 'view',
                'qa-review' => 'none',
                'bank-verification' => 'none',
                'peregrine' => 'none',
                'ravens' => 'none',
                'retention' => 'view',
                'chargebacks' => 'view',
                'partners' => 'none',
                'carriers' => 'none',
                'payroll' => 'none',
                'chart-of-accounts' => 'none',
                'general-ledger' => 'none',
                'petty-cash' => 'none',
                'pabs-tickets' => 'none',
                'revenue-analytics' => 'none',
                'live-analytics' => 'none',
                'users' => 'none',
                'settings' => 'none',
                'audit-logs' => 'none',
                'duplicate-checker' => 'none',
                'epms' => 'none',
                'chat' => 'full',
                'announcements' => 'view',
            ],

            'Verifier' => [
                'ems' => 'none',
                'attendance' => 'view',
                'dock' => 'view',
                'holidays' => 'view',
                'leads' => 'none',
                'sales' => 'view',
                'issuance' => 'view',
                'qa-review' => 'none',
                'bank-verification' => 'none',
                'peregrine' => 'full',
                'ravens' => 'none',
                'retention' => 'none',
                'chargebacks' => 'none',
                'partners' => 'none',
                'carriers' => 'none',
                'payroll' => 'none',
                'chart-of-accounts' => 'none',
                'general-ledger' => 'none',
                'petty-cash' => 'none',
                'pabs-tickets' => 'none',
                'revenue-analytics' => 'none',
                'live-analytics' => 'none',
                'users' => 'none',
                'settings' => 'none',
                'audit-logs' => 'none',
                'duplicate-checker' => 'none',
                'epms' => 'none',
                'chat' => 'full',
                'announcements' => 'view',
            ],

            'Peregrine Closer' => [
                'ems' => 'none',
                'attendance' => 'view',
                'dock' => 'view',
                'holidays' => 'view',
                'leads' => 'none',
                'sales' => 'view',
                'issuance' => 'view',
                'qa-review' => 'none',
                'bank-verification' => 'view',
                'peregrine' => 'full',
                'ravens' => 'none',
                'retention' => 'none',
                'chargebacks' => 'none',
                'partners' => 'none',
                'carriers' => 'none',
                'payroll' => 'none',
                'chart-of-accounts' => 'none',
                'general-ledger' => 'none',
                'petty-cash' => 'none',
                'pabs-tickets' => 'none',
                'revenue-analytics' => 'none',
                'live-analytics' => 'none',
                'users' => 'none',
                'settings' => 'none',
                'audit-logs' => 'none',
                'duplicate-checker' => 'none',
                'epms' => 'none',
                'chat' => 'full',
                'announcements' => 'view',
            ],

            'Peregrine Validator' => [
                'ems' => 'none',
                'attendance' => 'view',
                'dock' => 'view',
                'holidays' => 'view',
                'leads' => 'none',
                'sales' => 'view',
                'issuance' => 'view',
                'qa-review' => 'none',
                'bank-verification' => 'none',
                'peregrine' => 'full',
                'ravens' => 'none',
                'retention' => 'none',
                'chargebacks' => 'none',
                'partners' => 'none',
                'carriers' => 'none',
                'payroll' => 'none',
                'chart-of-accounts' => 'none',
                'general-ledger' => 'none',
                'petty-cash' => 'none',
                'pabs-tickets' => 'none',
                'revenue-analytics' => 'none',
                'live-analytics' => 'none',
                'users' => 'none',
                'settings' => 'none',
                'audit-logs' => 'none',
                'duplicate-checker' => 'none',
                'epms' => 'none',
                'chat' => 'full',
                'announcements' => 'view',
            ],

            'Ravens Closer' => [
                'ems' => 'none',
                'attendance' => 'view',
                'dock' => 'view',
                'holidays' => 'view',
                'leads' => 'none',
                'sales' => 'view',
                'issuance' => 'view',
                'qa-review' => 'none',
                'bank-verification' => 'view',
                'peregrine' => 'none',
                'ravens' => 'full',
                'retention' => 'none',
                'chargebacks' => 'none',
                'partners' => 'none',
                'carriers' => 'none',
                'payroll' => 'none',
                'chart-of-accounts' => 'none',
                'general-ledger' => 'none',
                'petty-cash' => 'none',
                'pabs-tickets' => 'none',
                'revenue-analytics' => 'none',
                'live-analytics' => 'none',
                'users' => 'none',
                'settings' => 'none',
                'audit-logs' => 'none',
                'duplicate-checker' => 'none',
                'epms' => 'none',
                'chat' => 'full',
                'announcements' => 'view',
            ],

            'Retention Officer' => [
                'ems' => 'none',
                'attendance' => 'view',
                'dock' => 'view',
                'holidays' => 'view',
                'leads' => 'none',
                'sales' => 'view',
                'issuance' => 'view',
                'qa-review' => 'none',
                'bank-verification' => 'none',
                'peregrine' => 'none',
                'ravens' => 'none',
                'retention' => 'full',
                'chargebacks' => 'full',
                'partners' => 'none',
                'carriers' => 'none',
                'payroll' => 'none',
                'chart-of-accounts' => 'none',
                'general-ledger' => 'none',
                'petty-cash' => 'none',
                'pabs-tickets' => 'none',
                'revenue-analytics' => 'none',
                'live-analytics' => 'none',
                'users' => 'none',
                'settings' => 'none',
                'audit-logs' => 'none',
                'duplicate-checker' => 'none',
                'epms' => 'none',
                'chat' => 'full',
                'announcements' => 'view',
            ],
        ];

        // Seed permissions for each role
        foreach ($defaultPermissions as $roleName => $permissions) {
            if (!isset($roles[$roleName])) {
                $this->command->warn("Role '{$roleName}' not found. Skipping...");
                continue;
            }

            $role = $roles[$roleName];

            foreach ($permissions as $moduleSlug => $level) {
                if (!isset($modules[$moduleSlug])) {
                    $this->command->warn("Module '{$moduleSlug}' not found. Skipping...");
                    continue;
                }

                RoleModulePermission::updateOrCreate(
                    [
                        'role_id' => $role->id,
                        'module_id' => $modules[$moduleSlug]->id,
                    ],
                    [
                        'permission_level' => $level,
                    ]
                );
            }

            $this->command->info("Permissions seeded for role: {$roleName}");
        }

        $this->command->info('Default permissions seeded successfully!');
    }
}
