<?php

namespace Database\Seeders;

use App\Models\Module;
use App\Models\RoleModulePermission;
use App\Support\Roles;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;

class DefaultPermissionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * This seeds default permissions based on the current role-based access control
     * defined in routes/web.php
     */
    public function run(): void
    {
        $this->command->info('Seeding default permissions...');

        // Get all roles and modules
        $roles = Role::all()->keyBy('name');
        $modules = Module::all()->keyBy('slug');

        // Define default permissions for each role
        $defaultPermissions = [
            Roles::SUPER_ADMIN => [
                // Super Admin gets full access to everything
                'dashboard' => 'full',
                'leads-peregrine' => 'full',
                'ems' => 'full',
                'attendance' => 'full',
                'dock' => 'full',
                'holidays' => 'full',
                'leads' => 'full',
                'sales' => 'full',
                'issuance' => 'full',
                'qa-review' => 'full',
                'bank-verification' => 'full',
                'peregrine' => 'full',
                'peregrine-dashboard' => 'full',
                'peregrine-verifier' => 'full',
                'peregrine-closers' => 'full',
                'peregrine-validation' => 'full',
                'ravens' => 'full',
                'ravens-dashboard' => 'full',
                'ravens-calling' => 'full',
                'ravens-bad-leads' => 'full',
                'ravens-followups' => 'full',
                'retention' => 'full',
                'chargebacks' => 'full',
                'partners' => 'full',
                'carriers' => 'full',
                'payroll' => 'full',
                'chart-of-accounts' => 'full',
                'general-ledger' => 'full',
                'petty-cash' => 'full',
                'pabs-tickets' => 'full',
                'revenue-analytics' => 'full',
                'live-analytics' => 'full',
                'users' => 'full',
                'settings' => 'full',
                'duplicate-checker' => 'full',
                'account-switch-log' => 'full',
                'epms' => 'full',
            ],
            
            Roles::CEO => [
                'dashboard' => 'full',
                'leads-peregrine' => 'full',
                'ems' => 'full',
                'attendance' => 'full',
                'dock' => 'full',
                'holidays' => 'full',
                'leads' => 'full',
                'sales' => 'full',
                'issuance' => 'full',
                'qa-review' => 'full',
                'bank-verification' => 'full',
                'peregrine' => 'full',
                'peregrine-dashboard' => 'full',
                'peregrine-verifier' => 'full',
                'peregrine-closers' => 'full',
                'peregrine-validation' => 'full',
                'ravens' => 'full',
                'ravens-dashboard' => 'full',
                'ravens-calling' => 'full',
                'ravens-bad-leads' => 'full',
                'ravens-followups' => 'full',
                'retention' => 'full',
                'chargebacks' => 'full',
                'partners' => 'full',
                'carriers' => 'full',
                'payroll' => 'full',
                'chart-of-accounts' => 'full',
                'general-ledger' => 'full',
                'petty-cash' => 'full',
                'pabs-tickets' => 'full',
                'revenue-analytics' => 'full',
                'live-analytics' => 'full',
                'users' => 'full',
                'settings' => 'view',
                'duplicate-checker' => 'full',
                'account-switch-log' => 'view',
                'epms' => 'full',
            ],

            Roles::MANAGER => [
                'dashboard' => 'full',
                'leads-peregrine' => 'full',
                'ems' => 'full',
                'attendance' => 'full',
                'dock' => 'full',
                'holidays' => 'full',
                'leads' => 'full',
                'sales' => 'full',
                'issuance' => 'full',
                'qa-review' => 'full',
                'bank-verification' => 'full',
                'peregrine' => 'full',
                'peregrine-dashboard' => 'full',
                'peregrine-verifier' => 'full',
                'peregrine-closers' => 'full',
                'peregrine-validation' => 'full',
                'ravens' => 'full',
                'ravens-dashboard' => 'full',
                'ravens-calling' => 'full',
                'ravens-bad-leads' => 'full',
                'ravens-followups' => 'full',
                'retention' => 'full',
                'chargebacks' => 'full',
                'partners' => 'full',
                'carriers' => 'full',
                'payroll' => 'view',
                'chart-of-accounts' => 'full',
                'general-ledger' => 'full',
                'petty-cash' => 'view',
                'pabs-tickets' => 'full',
                'revenue-analytics' => 'full',
                'live-analytics' => 'full',
                'users' => 'edit',
                'settings' => 'view',
                'duplicate-checker' => 'full',
                'account-switch-log' => 'view',
                'epms' => 'view',
            ],

            Roles::COORDINATOR => [
                'dashboard' => 'full',
                'leads-peregrine' => 'edit',
                'ems' => 'full',
                'attendance' => 'full',
                'dock' => 'full',
                'holidays' => 'full',
                'leads' => 'edit',
                'sales' => 'full',
                'issuance' => 'full',
                'qa-review' => 'full',
                'bank-verification' => 'full',
                'peregrine' => 'full',
                'peregrine-dashboard' => 'full',
                'peregrine-verifier' => 'full',
                'peregrine-closers' => 'full',
                'peregrine-validation' => 'full',
                'ravens' => 'full',
                'ravens-dashboard' => 'full',
                'ravens-calling' => 'full',
                'ravens-bad-leads' => 'full',
                'ravens-followups' => 'full',
                'retention' => 'full',
                'chargebacks' => 'full',
                'partners' => 'full',
                'carriers' => 'full',
                'payroll' => 'full',
                'chart-of-accounts' => 'full',
                'general-ledger' => 'full',
                'petty-cash' => 'full',
                'pabs-tickets' => 'full',
                'revenue-analytics' => 'full',
                'live-analytics' => 'full',
                'users' => 'full',
                'settings' => 'view',
                'duplicate-checker' => 'full',
                'account-switch-log' => 'full',
                'epms' => 'view',
            ],

            Roles::HR => [
                'dashboard' => 'none',
                'leads-peregrine' => 'none',
                'ems' => 'full',
                'attendance' => 'full',
                'dock' => 'edit',
                'holidays' => 'full',
                'leads' => 'none',
                'sales' => 'view',
                'issuance' => 'view',
                'qa-review' => 'view',
                'bank-verification' => 'none',
                'peregrine' => 'none',
                'peregrine-dashboard' => 'none',
                'peregrine-verifier' => 'none',
                'peregrine-closers' => 'none',
                'peregrine-validation' => 'none',
                'ravens' => 'none',
                'ravens-dashboard' => 'none',
                'ravens-calling' => 'none',
                'ravens-bad-leads' => 'none',
                'ravens-followups' => 'none',
                'retention' => 'view',
                'chargebacks' => 'view',
                'partners' => 'view',
                'carriers' => 'view',
                'payroll' => 'view',
                'chart-of-accounts' => 'none',
                'general-ledger' => 'none',
                'petty-cash' => 'none',
                'pabs-tickets' => 'none',
                'revenue-analytics' => 'none',
                'live-analytics' => 'none',
                'users' => 'edit',
                'settings' => 'none',
                'duplicate-checker' => 'none',
                'account-switch-log' => 'none',
                'epms' => 'none',
            ],

            Roles::QA => [
                'dashboard' => 'none',
                'leads-peregrine' => 'none',
                'ems' => 'view',
                'attendance' => 'view',
                'dock' => 'full',
                'holidays' => 'view',
                'leads' => 'view',
                'sales' => 'view',
                'issuance' => 'view',
                'qa-review' => 'full',
                'bank-verification' => 'view',
                'peregrine' => 'view',
                'peregrine-dashboard' => 'view',
                'peregrine-verifier' => 'view',
                'peregrine-closers' => 'view',
                'peregrine-validation' => 'view',
                'ravens' => 'view',
                'ravens-dashboard' => 'view',
                'ravens-calling' => 'view',
                'ravens-bad-leads' => 'view',
                'ravens-followups' => 'view',
                'retention' => 'view',
                'chargebacks' => 'view',
                'partners' => 'none',
                'carriers' => 'none',
                'payroll' => 'none',
                'chart-of-accounts' => 'none',
                'general-ledger' => 'none',
                'petty-cash' => 'none',
                'pabs-tickets' => 'none',
                'revenue-analytics' => 'none',
                'live-analytics' => 'none',
                'users' => 'none',
                'settings' => 'none',
                'duplicate-checker' => 'none',
                'account-switch-log' => 'none',
                'epms' => 'none',
            ],

            Roles::EMPLOYEE => [
                'dashboard' => 'none',
                'leads-peregrine' => 'none',
                'ems' => 'none',
                'attendance' => 'view',
                'dock' => 'view',
                'holidays' => 'view',
                'leads' => 'none',
                'sales' => 'edit',
                'issuance' => 'view',
                'qa-review' => 'none',
                'bank-verification' => 'none',
                'peregrine' => 'none',
                'peregrine-dashboard' => 'none',
                'peregrine-verifier' => 'none',
                'peregrine-closers' => 'none',
                'peregrine-validation' => 'none',
                'ravens' => 'none',
                'ravens-dashboard' => 'none',
                'ravens-calling' => 'none',
                'ravens-bad-leads' => 'none',
                'ravens-followups' => 'none',
                'retention' => 'view',
                'chargebacks' => 'view',
                'partners' => 'none',
                'carriers' => 'none',
                'payroll' => 'none',
                'chart-of-accounts' => 'none',
                'general-ledger' => 'none',
                'petty-cash' => 'none',
                'pabs-tickets' => 'none',
                'revenue-analytics' => 'none',
                'live-analytics' => 'none',
                'users' => 'none',
                'settings' => 'none',
                'duplicate-checker' => 'none',
                'account-switch-log' => 'none',
                'epms' => 'none',
            ],

            Roles::VERIFIER => [
                'dashboard' => 'none',
                'leads-peregrine' => 'none',
                'ems' => 'none',
                'attendance' => 'view',
                'dock' => 'view',
                'holidays' => 'view',
                'leads' => 'none',
                'sales' => 'view',
                'issuance' => 'view',
                'qa-review' => 'none',
                'bank-verification' => 'none',
                'peregrine' => 'full',
                'peregrine-dashboard' => 'full',
                'peregrine-verifier' => 'full',
                'peregrine-closers' => 'none',
                'peregrine-validation' => 'none',
                'ravens' => 'none',
                'ravens-dashboard' => 'none',
                'ravens-calling' => 'none',
                'ravens-bad-leads' => 'none',
                'ravens-followups' => 'none',
                'retention' => 'none',
                'chargebacks' => 'none',
                'partners' => 'none',
                'carriers' => 'none',
                'payroll' => 'none',
                'chart-of-accounts' => 'none',
                'general-ledger' => 'none',
                'petty-cash' => 'none',
                'pabs-tickets' => 'none',
                'revenue-analytics' => 'none',
                'live-analytics' => 'none',
                'users' => 'none',
                'settings' => 'none',
                'duplicate-checker' => 'none',
                'account-switch-log' => 'none',
                'epms' => 'none',
            ],

            Roles::PEREGRINE_CLOSER => [
                'dashboard' => 'none',
                'leads-peregrine' => 'none',
                'ems' => 'none',
                'attendance' => 'view',
                'dock' => 'view',
                'holidays' => 'view',
                'leads' => 'none',
                'sales' => 'view',
                'issuance' => 'view',
                'qa-review' => 'none',
                'bank-verification' => 'view',
                'peregrine' => 'full',
                'peregrine-dashboard' => 'none',
                'peregrine-verifier' => 'none',
                'peregrine-closers' => 'full',
                'peregrine-validation' => 'none',
                'ravens' => 'none',
                'ravens-dashboard' => 'none',
                'ravens-calling' => 'none',
                'ravens-bad-leads' => 'none',
                'ravens-followups' => 'none',
                'retention' => 'none',
                'chargebacks' => 'none',
                'partners' => 'none',
                'carriers' => 'none',
                'payroll' => 'none',
                'chart-of-accounts' => 'none',
                'general-ledger' => 'none',
                'petty-cash' => 'none',
                'pabs-tickets' => 'none',
                'revenue-analytics' => 'none',
                'live-analytics' => 'none',
                'users' => 'none',
                'settings' => 'none',
                'duplicate-checker' => 'none',
                'account-switch-log' => 'none',
                'epms' => 'none',
            ],

            Roles::PEREGRINE_VALIDATOR => [
                'dashboard' => 'none',
                'leads-peregrine' => 'none',
                'ems' => 'none',
                'attendance' => 'view',
                'dock' => 'view',
                'holidays' => 'view',
                'leads' => 'none',
                'sales' => 'view',
                'issuance' => 'view',
                'qa-review' => 'none',
                'bank-verification' => 'none',
                'peregrine' => 'full',
                'peregrine-dashboard' => 'none',
                'peregrine-verifier' => 'none',
                'peregrine-closers' => 'none',
                'peregrine-validation' => 'full',
                'ravens' => 'none',
                'ravens-dashboard' => 'none',
                'ravens-calling' => 'none',
                'ravens-bad-leads' => 'none',
                'ravens-followups' => 'none',
                'retention' => 'none',
                'chargebacks' => 'none',
                'partners' => 'none',
                'carriers' => 'none',
                'payroll' => 'none',
                'chart-of-accounts' => 'none',
                'general-ledger' => 'none',
                'petty-cash' => 'none',
                'pabs-tickets' => 'none',
                'revenue-analytics' => 'none',
                'live-analytics' => 'none',
                'users' => 'none',
                'settings' => 'none',
                'duplicate-checker' => 'none',
                'account-switch-log' => 'none',
                'epms' => 'none',
            ],

            Roles::RAVENS_CLOSER => [
                'dashboard' => 'none',
                'leads-peregrine' => 'none',
                'ems' => 'none',
                'attendance' => 'view',
                'dock' => 'view',
                'holidays' => 'view',
                'leads' => 'none',
                'sales' => 'view',
                'issuance' => 'view',
                'qa-review' => 'none',
                'bank-verification' => 'view',
                'peregrine' => 'none',
                'peregrine-dashboard' => 'none',
                'peregrine-verifier' => 'none',
                'peregrine-closers' => 'none',
                'peregrine-validation' => 'none',
                'ravens' => 'full',
                'ravens-dashboard' => 'full',
                'ravens-calling' => 'full',
                'ravens-bad-leads' => 'full',
                'ravens-followups' => 'full',
                'retention' => 'none',
                'chargebacks' => 'none',
                'partners' => 'none',
                'carriers' => 'none',
                'payroll' => 'none',
                'chart-of-accounts' => 'none',
                'general-ledger' => 'none',
                'petty-cash' => 'none',
                'pabs-tickets' => 'none',
                'revenue-analytics' => 'none',
                'live-analytics' => 'none',
                'users' => 'none',
                'settings' => 'none',
                'duplicate-checker' => 'none',
                'account-switch-log' => 'none',
                'epms' => 'none',
            ],

            Roles::RETENTION_OFFICER => [
                'dashboard' => 'view',
                'leads-peregrine' => 'none',
                'ems' => 'none',
                'attendance' => 'view',
                'dock' => 'view',
                'holidays' => 'view',
                'leads' => 'none',
                'sales' => 'view',
                'issuance' => 'view',
                'qa-review' => 'none',
                'bank-verification' => 'none',
                'peregrine' => 'none',
                'peregrine-dashboard' => 'none',
                'peregrine-verifier' => 'none',
                'peregrine-closers' => 'none',
                'peregrine-validation' => 'none',
                'ravens' => 'none',
                'ravens-dashboard' => 'none',
                'ravens-calling' => 'none',
                'ravens-bad-leads' => 'none',
                'ravens-followups' => 'none',
                'retention' => 'full',
                'chargebacks' => 'full',
                'partners' => 'none',
                'carriers' => 'none',
                'payroll' => 'none',
                'chart-of-accounts' => 'none',
                'general-ledger' => 'none',
                'petty-cash' => 'none',
                'pabs-tickets' => 'none',
                'revenue-analytics' => 'none',
                'live-analytics' => 'none',
                'users' => 'none',
                'settings' => 'none',
                'duplicate-checker' => 'none',
                'account-switch-log' => 'none',
                'epms' => 'none',
            ],
        ];

        // Seed permissions for each role
        foreach ($defaultPermissions as $roleName => $permissions) {
            if (!isset($roles[$roleName])) {
                $this->command->warn("Role '{$roleName}' not found. Skipping...");
                continue;
            }

            $role = $roles[$roleName];

            foreach ($permissions as $moduleSlug => $level) {
                if (!isset($modules[$moduleSlug])) {
                    $this->command->warn("Module '{$moduleSlug}' not found. Skipping...");
                    continue;
                }

                RoleModulePermission::updateOrCreate(
                    [
                        'role_id' => $role->id,
                        'module_id' => $modules[$moduleSlug]->id,
                    ],
                    [
                        'permission_level' => $level,
                    ]
                );
            }

            $this->command->info("Permissions seeded for role: {$roleName}");
        }

        $this->command->info('Default permissions seeded successfully!');
    }
}
